### ISSUE TITLE
feature request:  selection box CSS customization.

### ISSUE THREAD

**Issue by aliveornot** [daybrush/selecto#96]
## Environments
* Framework name:  react. (but the requested feature is framework-agnostic)
* Framework version: 
* Component name:  selecto
* Component version:
* Testable Address(optional): 

## Description
Before start, kudos to your impressive work! It helps me a lot! 

It would be great if the css styling of .selecto-selection div (i.e. the skyblue rectangle displayed when I drag, to indicate the selected region) can be customized. 
![image](https://user-images.githubusercontent.com/60848153/184056077-7d9265b6-95cc-4426-bffb-cb146701cfc6.png)

The motivation: 
1. I have two different type of selection mode in my app. It would be great if I can display it intuitively.
2. Plus, I think selecto can potentially be used to DRAW a <div/> in real time, in which case, transparent background rectangle is more appropriate than the sky blue one.  

Thanks a lot!

**Comment by daybrush** [comment]
@aliveornot 

For now, I have no choice but to tell you to process it with css.

There is a way to force assignment using !important.

```css
.selecto-selection {
    position: fixed;
    display: none;
    border: 1px solid #4af;
    background: rgba(68, 170, 255, 0.5);
    pointer-events: none;
    will-change: transform;
    z-index: 100;
}
```
